#!/bin/bash
echo " Setting up audio verses, about 25 MB"
sudo unzip -d ~/.Bhagavadgeeta/ geeta
echo "Setting up the player "
sudo apt-get install mplayer
chmod +x playgeeta
cp playgeeta /usr/bin/playgeeta
echo " done !!"
echo " use playgeeta -h for help"

